import PropTypes from "prop-types";
import { useTranslation } from "react-i18next";

function CountryName({ info }) {
  const [t] = useTranslation("translation");
  const countryInfo = {
    AD: t("Andorra"),
    AE: t("United Arab Emirates"),
    AF: t("Afghanistan"),
    AG: t("Antigua and Barbuda"),
    AI: t("Anguilla"),
    AL: t("Armenia"),
    AN: t("Netherlands Antilles"),
    AO: t("Angola"),
    AQ: t("Antarctica"),
    AR: t("Argentina"),
    AS: t("American Samoa"),
    AT: t("Austria"),
    AU: t("Australia"),
    AW: t("Aruba"),
    AZ: t("Azerbaijan"),
    BA: t("Bosnia and Herzegovina"),
    BB: t("Barbados"),
    BD: t("Bangladesh"),
    BE: t("Belgium"),
    BF: t("Burkina Faso"),
    BG: t("Bulgaria"),
    BH: t("Bahrain"),
    BI: t("Burundi"),
    BJ: t("Benin"),
    BM: t("Bermuda"),
    BN: t("Brunei"),
    BO: t("Bolivia"),
    BR: t("Brazil"),
    BS: t("Bahamas"),
    BT: t("Bhutan"),
    BV: t("Bouvet Island"),
    BW: t("Botswana"),
    BY: t("Belarus"),
    BZ: t("Belize"),
    CA: t("Canada"),
    CC: t("Cocos (Keeling) Islands"),
    CD: t("Democratic Republic of the Congo (Kinshasa)"),
    CF: t("Central African Republic"),
    CG: t("Republic of the Congo (Brazzaville)"),
    CH: t("Switzerland"),
    CI: t("Ivory Coast"),
    CK: t("Cook Islands"),
    CL: t("Chile"),
    CM: t("Cameroon"),
    CN: t("China"),
    CO: t("Colombia"),
    CR: t("Costa Rica"),
    CS: t("Serbia and Montenegro"),
    CU: t("Cuba"),
    CV: t("Cape Verde"),
    CX: t("Christmas Island"),
    CY: t("Cyprus"),
    CZ: t("Czech Republic"),
    DE: t("Germany"),
    DJ: t("Djibouti"),
    DK: t("Denmark"),
    DM: t("Dominica"),
    DO: t("Dominican Republic"),
    DZ: t("Algeria"),
    EC: t("Ecuador"),
    EE: t("Estonia"),
    EG: t("Egypt"),
    EH: t("Western Sahara"),
    ER: t("Eritrea"),
    ES: t("Spain"),
    ET: t("Ethiopia"),
    FI: t("Finland"),
    FJ: t("Fiji"),
    FK: t("Falkland Islands"),
    FM: t("Micronesia"),
    FO: t("Faroe Islands"),
    FR: t("France"),
    GA: t("Gabon"),
    GB: t("United Kingdom"),
    GD: t("Grenada"),
    GE: t("Georgia"),
    GF: t("French Guiana"),
    GH: t("Ghana"),
    GI: t("Gibraltar"),
    GL: t("Greenland"),
    GM: t("Gambia"),
    GP: t("Guadeloupe"),
    GQ: t("Equatorial Guinea"),
    GS: t("South Georgia and the South Sandwich Islands"),
    GT: t("Guatemala"),
    GU: t("Guam"),
    GW: t("Guinea-Bissau"),
    GY: t("Guyana"),
    HK: t("Hong Kong SAR China"),
    HM: t("Heard Island and McDonald Islands"),
    HN: t("Honduras"),
    HR: t("Croatia"),
    HT: t("Haiti"),
    HU: t("Hungary"),
    ID: t("Indonesia"),
    IE: t("Ireland"),
    IL: t("Israel"),
    IN: t("India"),
    IO: t("British Indian Ocean Territory"),
    IQ: t("Iraq"),
    IR: t("Iran"),
    IS: t("Iceland"),
    IT: t("Italy"),
    JM: t("Jamaica"),
    JO: t("Jordan"),
    JP: t("Japan"),
    KE: t("Kenya"),
    KG: t("Kyrgyzstan"),
    KH: t("Cambodia"),
    KI: t("Kiribati"),
    KM: t("Comoros"),
    KN: t("Saint Kitts and Nevis"),
    KP: t("North Korea"),
    KR: t("South Korea"),
    KW: t("Kuwait"),
    KY: t("Cayman Islands"),
    KZ: t("Kazakhstan"),
    LA: t("Lao People's Democratic Republic"),
    LB: t("Lebanon"),
    LC: t("Saint Lucia"),
    LI: t("Liechtenstein"),
    LK: t("Sri Lanka"),
    LR: t("Liberia"),
    LS: t("Lesotho"),
    LT: t("Lithuania"),
    LU: t("Luxembourg"),
    LV: t("Latvia"),
    LY: t("Libyan Arab Jamahiriya"),
    MA: t("Morocco"),
    MC: t("Monaco"),
    MD: t("Moldova"),
    ME: t("Montenegro"),
    MG: t("Madagascar"),
    MH: t("Marshall Islands"),
    MK: t("Macedonia"),
    ML: t("Mali"),
    MM: t("Myanmar (Burma)"),
    MN: t("Mongolia"),
    MO: t("Macau SAR China"),
    MP: t("Northern Mariana Islands"),
    MQ: t("Martinique"),
    MR: t("Mauritania"),
    MS: t("Montserrat"),
    MT: t("Malta"),
    MU: t("Mauritius"),
    MV: t("Maldives"),
    MW: t("Malawi"),
    MX: t("Mexico"),
    MY: t("Malaysia"),
    MZ: t("Mozambique"),
    NA: t("Namibia"),
    NC: t("New Caledonia"),
    NE: t("Niger"),
    NF: t("Norfolk Island"),
    NG: t("Nigeria"),
    NI: t("Nicaragua"),
    NL: t("Netherlands"),
    NO: t("Norway"),
    NP: t("Nepal"),
    NR: t("Nauru"),
    NU: t("Niue"),
    NZ: t("New Zealand"),
    OM: t("Oman"),
    PA: t("Panama"),
    PE: t("Peru"),
    PF: t("French Polynesia"),
    PG: t("Papua New Guinea"),
    PH: t("Philippines"),
    PK: t("Pakistan"),
    PL: t("Poland"),
    PM: t("Saint Pierre and Miquelon"),
    PN: t("Pitcairn Islands"),
    PR: t("Puerto Rico"),
    PS: t("Palestinian Territory"),
    PT: t("Portugal"),
    PW: t("Palau"),
    PY: t("Paraguay"),
    QA: t("Qatar"),
    RE: t("Reunion"),
    RO: t("Romania"),
    RS: t("Serbia"),
    RU: t("Russia"),
    RW: t("Rwanda"),
    SA: t("Saudi Arabia"),
    SB: t("Solomon Islands"),
    SC: t("Seychelles"),
    SD: t("Sudan"),
    SE: t("Sweden"),
    SG: t("Singapore"),
    SH: t("Saint Helena"),
    SI: t("Slovenia"),
    SJ: t("Svalbard and Jan Mayen Islands"),
    SK: t("Slovakia"),
    SL: t("Sierra Leone"),
    SM: t("San Marino"),
    SN: t("Senegal"),
    SO: t("Somalia"),
    SR: t("Suriname"),
    SS: t("South Sudan"),
    ST: t("Sao Tome and Principe"),
    SU: t("Soviet Union"),
    SV: t("El Salvador"),
    SY: t("Syrian Arab Republic"),
    SZ: t("Eswatini (Swaziland)"),
    TC: t("Turks and Caicos Islands"),
    TD: t("Chad"),
    TF: t("French Southern Territories"),
    TG: t("Togo"),
    TH: t("Thailand"),
    TJ: t("Tajikistan"),
    TK: t("Tokelau"),
    TL: t("Timor-Leste"),
    TM: t("Turkmenistan"),
    TN: t("Tunisia"),
    TO: t("Tonga"),
    TR: t("Turkey"),
    TT: t("Trinidad and Tobago"),
    TV: t("Tuvalu"),
    TW: t("Taiwan"),
    TZ: t("Tanzania"),
    UA: t("Ukraine"),
    UG: t("Uganda"),
    UM: t("United States Minor Outlying Islands"),
    US: t("United States of America"),
    UY: t("Uruguay"),
    UZ: t("Uzbekistan"),
    VA: t("Vatican City"),
    VC: t("Saint Vincent and the Grenadines"),
    VE: t("Venezuela"),
    VG: t("British Virgin Islands"),
    VI: t("U.S. Virgin Islands"),
    VN: t("Vietnam"),
    VU: t("Vanuatu"),
    WF: t("Wallis and Futuna Islands"),
    WS: t("Samoa"),
    XC: t("Czechoslovakia"),
    XG: t("East Germany"),
    XK: t("Kosovo"),
    YE: t("Yemen"),
    YT: t("Mayotte"),
    YU: t("Yugoslavia"),
    ZA: t("South Africa"),
    ZM: t("Zambia"),
  };
  const countryName = countryInfo[info] || "No Data";
  return (
    <div className="inline-block pr-1">
      {countryName !== "No Data" && countryName}
    </div>
  );
}

export default CountryName;

CountryName.defaultProps = {
  info: PropTypes.string,
};

CountryName.propTypes = {
  info: PropTypes.string,
};
